version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "5244:5244"
      - "1000:1000"
      - "555:555"
      - "556:556"
      - "557:557"
