version: '3.3'
services:
  master: 
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "crawlab-pvc:/data"
    ports:    
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    container_name: crawlab_example_mongo
    restart: always
    volumes:
      - "crawlab-pvc:/data"
    
volumes:
  crawlab-pvc:
    driver_opts:
      class: csi-okteto-standard
